### ISSUE TITLE
Improve handling of !important transformation specificity

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1073]
On https://scalewp.io/development-and-workflow/ there is an element:

```html
<header id="header" style="display: none;">
```

In spite of the inline style, it gets shown because the stylesheet has:

```css
#header {
    display: block !important;
    width: 100%;
    background: #FFF;
}
```

Nevertheless, when it is served as AMP ***the header is not displayed***. The inline `style` is currently getting converted into a style rule as follows:

```css
:root:not(#_):not(#_):not(#_):not(#_):not(#_) .amp-wp-224b51a {
    display: none;
}
```

And the `!important` property gets extracted into a separate rule as:

```css
:root:not(#_) #header {
    display: block;
}
```

Something is wrong in the logic because currently the header is not appearing in AMP where it is appearing in non-AMP. In other words, the generated selector for the inline style `:root:not(#_):not(#_):not(#_):not(#_):not(#_) .amp-wp-224b51a` is winning over an `!important` property in an ID-selector style rule which gets transformed as `:root:not(#_) #header`.

Something needs to change in the `collect_inline_styles` and `transform_important_qualifiers` methods:

https://github.com/Automattic/amp-wp/blob/6861830b80e2d2cc17306f034feef976c35f6e22/includes/sanitizers/class-amp-style-sanitizer.php#L1064-L1102

and

https://github.com/Automattic/amp-wp/blob/6861830b80e2d2cc17306f034feef976c35f6e22/includes/sanitizers/class-amp-style-sanitizer.php#L981-L1048
