### ISSUE TITLE
Remove IE hacks from stylesheets since fail AMP validation

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1099]
AMP validation fails on IE hacks, for example:

```css
textarea {
	font-size: 100%; /* Corrects font size not being inherited in all browsers */
	margin: 0; /* Addresses margins set differently in IE6/7, F3/4, S5, Chrome */
	vertical-align: baseline; /* Improves appearance and consistency in all browsers */
	*vertical-align: middle; /* Improves appearance and consistency in IE6/IE7 */
}
```

Results in:

![image](https://user-images.githubusercontent.com/134745/39338315-ea6e94fe-4976-11e8-81ac-2343bc9e47cc.png)

The CSS parser now part of the plugin is supposed to support an awareness of IE hacks, so it's possible that we could be able to automatically delete any property that has such a hack with something like this:

```diff
--- a/includes/sanitizers/class-amp-style-sanitizer.php
+++ b/includes/sanitizers/class-amp-style-sanitizer.php
@@ -901,6 +901,13 @@ class AMP_Style_Sanitizer extends AMP_Base_Sanitizer {
 			}
 		}
 
+		// Remove all properties that have IE hacks since they fail AMP validation.
+		foreach ( $ruleset->getRules() as $rule ) {
+			if ( 0 !== count( $rule->getIeHack() ) ) {
+				$ruleset->removeRule( $rule );
+			}
+		}
+
 		if ( $ruleset instanceof AtRuleSet && 'font-face' === $ruleset->atRuleName() ) {
 			$this->process_font_face_at_rule( $ruleset, $options );
 		}
```

The assumption is that IE hacks are obsolete since they target versions of IE that are long dead.
