### ISSUE TITLE
Legit CSS selector renamed

### ISSUE THREAD

**Issue by swissspidy** [Automattic/amp-wp#1513]
In my theme I have some code like this (simplified):

HTML:

```html
<body class="home">
  <div class="content-area">
    <article id="post-1234" class="post-1234 video type-video status-publish has-post-thumbnail hentry">
      <div class="entry-video">
        <iframe width="400" height="225" src="https://www.youtube.com/...."></iframe>
      </div>
    </article>
  </div>
</body>
```

CSS:

```css
.home .content-area .video {
  border-top: 5px solid red;
  padding: 21px .5em .5em;
  background: white;
}
```

With AMP active, it looks like this:

```html
<body class="home">
  <div class="content-area">
    <article id="post-1234" class="post-1234 video type-video status-publish has-post-thumbnail hentry">
      <div class="entry-video">
        <amp-youtube data-videoid="..." layout="responsive" width="600" height="338"></amp-youtube>
      </div>
    </article>
  </div>
</body>
```

CSS:

```css
.home .content-area .amp-video,
.home .content-area .amp-youtube {
  border-top: 5px solid red;
  padding: 21px .5em .5em;
  background: white;
}
```

As a result, my video container is unexpectedly unstyled when using AMP.

I've now fixed this by using `.type-video` instead of `.video` in my selector as a workaround.

However, I'm curious why this happens in the first place. Is `video` some kind of reserved keyword that's documented somewhere?
