### ISSUE TITLE
Inline css generating invalid CSS

### ISSUE THREAD

**Issue by beaucollins** [Automattic/amp-wp#1684]
I have a site with an unnecessary amount of inline styles due to copy/pasting Word content. However, the CSS generated in the header of the AMP version of the page appears to be invalid CSS (notice the extra `<br /></br>` tags:

```css
.amp-wp-inline-b1e4d4edade68d7a2546e25c02350ebe{<br /></br>   vertical-align:middle;line-height:15.0pt;text-align:center;}
```

It happens during the [`amp_post_template_add_styles`][amp_post_template_add_styles] function.

https://github.com/Automattic/amp-wp/blob/99d094341e5a011f71af4e934862097d8bf7be1b/includes/amp-post-template-actions.php#L101-L116

[amp_post_template_add_styles]: https://github.com/Automattic/amp-wp/blob/99d094341e5a011f71af4e934862097d8bf7be1b/includes/amp-post-template-actions.php#L101-L116

I'm not able to figure out what would be generating the `<br /></br>` tags, any clue?
