### ISSUE TITLE
The multi-column gallery is showing indifferent height in AMP mode.

### ISSUE THREAD

**Issue by deepaklalwani97** [Automattic/amp-wp#4723]
## Bug Description

The multi-column gallery is showing indifferent height in AMP mode and does not look consistent with the non-AMP mode when crop image toggle is enabled for the gallery block. In the AMP mode, the height is calculated differently resulting in the inconsistent look in AMP and non-AMP mode.

Issue 1:
By default, the Gallery block does not apply fixed height and width attributes to the `img` tag in the non-AMP mode. But the image sanitizer will apply default `height=400` and `width=750` to `amp-img` and `amp-anim` tags if based `img` tag does not have width and height defined.

Issue 2:
The gallery block by default enables the `crop images` setting on the non-AMP page which means following CSS is being applied to `img` tag in non-AMP mode.

``` CSS
height: 100%;
flex: 1;
object-fit: cover;
```
On AMP mode this CSS is being applied to `amp-img` or `amp-anim` tag. To make it consistent with non-AMP mode we need to apply above CSS on child `img` tag of parent `amp-img` or `amp-anim`.

## Expected Behaviour

The multi-column gallery images should have the same height and same cropped image behavior in both AMP and non-AMP mode. 

## Steps to reproduce

1. Create a post and add a multi-column gallery.
2. Use vertical images for the first image and horizontal image for the second image.
3. Enable the crop images toggle for the gallery block.
4. Compare the gallery images in both AMP and Non-AMP mode.

## Screenshots
![image](https://user-images.githubusercontent.com/32839217/81821943-2510c600-9550-11ea-830e-e0ea251d5c1d.png)

## Additional context

 - WordPress version: 5.4.1
 - Plugin version: 1.5.3
 - AMP plugin template mode: Transitional

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
> The gallery block by default enables the `crop images` setting on the non-AMP page which means following CSS is being applied to `img` tag in non-AMP mode.

What is the selector for this rule in the original CSS?

**Comment by sagarnasit** [comment]
@westonruter Original selector is `.wp-block-gallery.is-cropped .blocks-gallery-item img`
![image](https://user-images.githubusercontent.com/25276905/82186487-93ff6d80-9908-11ea-9344-462cfbf2876b.png)

**Comment by westonruter** [comment]
OK, thanks. And this applies to both GIF and non-GIF images, correct? 

The CSS in question is coming from core: https://github.com/WordPress/WordPress/blob/307725883a1783123051fef0650f1e4990dce0b0/wp-includes/css/dist/block-library/style.css#L560-L580

Either we add new CSS rule as follows:

```css
    @supports ((position: -webkit-sticky) or (position: sticky)) {
      .wp-block-gallery.is-cropped .blocks-gallery-image amp-img > img,
      .wp-block-gallery.is-cropped .blocks-gallery-image amp-anim > img,
      .wp-block-gallery.is-cropped .blocks-gallery-item amp-img > img,
      .wp-block-gallery.is-cropped .blocks-gallery-item amp-anim > img,
      .blocks-gallery-grid.is-cropped .blocks-gallery-image amp-img > img,
      .blocks-gallery-grid.is-cropped .blocks-gallery-image amp-anim > img,
      .blocks-gallery-grid.is-cropped .blocks-gallery-item amp-anim > img,
      .blocks-gallery-grid.is-cropped .blocks-gallery-item amp-img > img {
        height: 100%;
        flex: 1;
        object-fit: cover; } }
```

Which does not seem ideal. Or, what is likely better, is to hook into the generation of the Gallery block, and make sure that all `amp-img` and `amp-anim` elements get created with `object-fit="contain"` attributes.
