### ISSUE TITLE
Invalid URLs in CSS can leak validation errors

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5463]
## Bug Description

As discovered on a [support topic](https://wordpress.org/support/topic/css-syntax-error-in-tag-style-amp-custom-invalid-url/), consider CSS that includes an invalid URL supplied for a `url()` like so:

```css
@font-face {font-family: 'GE SS'; src: url(//:) format('no404'), url('fonts/ge-ss-med.ttf') format('truetype'); font-weight: normal; font-style: normal; font-display: swap;}
```

A validation error is picked up by the AMP validator for `//:`

> CSS syntax error in tag ‘style amp-custom’ – invalid url ‘//:’

## Expected Behaviour

Invalid URLs should be caught by the CSS sanitizer.

## Steps to reproduce

1. Place the above CSS in a `style` element, like in a Custom HTML block.
2. View the AMP page.
3. See validation error.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If a URL cannot be parsed successfully, a validation error should be raised. If the validation error is sanitized (invalid markup removed), then the property containing the `url()` should be removed (e.g. the `src`).

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*
