### ISSUE TITLE
support Element.classList.add and Element.classList.remove

### ISSUE THREAD

**Issue by pewgeuges** [Automattic/amp-wp#5913]
The lean implementation of styled tooltips requires to add and remove classes for the shown and hidden status.

**Comment by kristoferbaxter** [comment]
Transferred this issue to `amp-wp`, since this doesn't have to do with the implementation of WorkerDOM, but rather in the conversion of a document using Wordpress Plugins.

**Comment by milindmore22** [comment]
Hello @pewgeuges 

AMP pages do not allow custom javascript on AMP pages, so the AMP plugins remove them for you to produces valid AMP pages. You can however use [amp-script](https://amp.dev/documentation/components/amp-script/) component to use javascript on AMP pages with few [restrictions](https://github.com/ampproject/worker-dom/blob/main/web_compat_table.md) 

In your case I don't see why we need javascript to toggle footnote, this can be also achieved using a simple CSS tweak.

goto -> Dashboard-> Appearance -> Customize -> Addtional CSS -> paste bewow CSS
```css
html[amp] span.footnote_referrer:hover > span.footnote_tooltip {
	visibility:visible;
	opacity:1;
}
```
let me know if this resolves your issue

**Comment by pewgeuges** [comment]
> In your case I don't see why we need javascript to toggle footnote, this can be also achieved using a simple CSS tweak.
> 
> goto -> Dashboard-> Appearance -> Customize -> Addtional CSS -> paste bewow CSS
> 
> ```css
> html[amp] span.footnote_referrer:hover > span.footnote_tooltip {
> 	visibility:visible;
> 	opacity:1;
> }
> ```
> 
> let me know if this resolves your issue

@milindmore22,

This is fabulous! Thanks a lot! No need for JS to display fully fledged tooltips!

The only change needed was remove the root element and its attribute selector, as even when using an argument present it failed. The now working is:
```css
span.footnote_referrer:hover > span.footnote_tooltip {
	visibility:visible;
	opacity:1;
}
```

~~And the new issue is that fade-out parameters for delay and duration are now applied symmetrically to fade-in.~~

**Comment by pewgeuges** [comment]
@milindmore22,

Solved also with asymmetric transitions. The rules are now:
```css
span.footnote_referrer > span.footnote_tooltip {
	visibility: hidden;
	opacity: 0;
	transition-property: visibility, opacity;
	transition-delay: 500ms;
	transition-duration: 1s;
}
span.footnote_referrer:hover > span.footnote_tooltip {
	visibility: visible;
	opacity: 1;
	transition-property: visibility, opacity;
	transition-delay: 0;
	transition-duration: 200ms;
}
```
We’ll change the internal CSS accordingly (where values come in from settings).

Thank you very much for helping make the plugin AMP compatible!
