### ISSUE TITLE
Direct child combinators handled unpredictably, may cause CSS outages

### ISSUE THREAD

**Issue by anrghg** [Automattic/amp-wp#7239]
### Bug Description

When CSS contains `>`, AMP-WP may keep it or remove it. For instance, on a remote host it keeps the style rules in use, whether they contain direct child combinators or not, while on a local host, it keeps them only after the `>` symbols have been removed, else it discards those rules, resulting in unstyled message boxes, failing CSS tooltips, and thus a broken website.

Fortunately the `>` were unnecessary so they could be simply removed, resulting in streamlined code.

### Expected Behaviour

Rules with `>` are never removed entirely while used, only unnecessary combinators are removed.

### Screenshots

This is hard to document as it occurred locally, not on the web. Screenshots would show unstyled divs, missing CSS tooltips…

This seems to be an undocumented requirement/limitation, like the deprecated `scroll-margin[-*]` documented by combining ampproject/amphtml#34378 and ampproject/amphtml#35366

No matter, thankfully issues are fixed. Experience replaces documentation that Google Search wouldn’t bring up like it points to the abovecited scroll offset at the very top of SRP.

### PHP Version

7.4.21	

### Plugin Version

2.3.0

### AMP plugin template mode

Standard

### WordPress Version

6.0.2

**Comment by westonruter** [comment]
Do you have the full CSS code sample that can trigger the issue?

**Comment by anrghg** [comment]
The example of message boxes was this combinator that caused discarding this ruleset. The fully configurable rules are in a PHP file:
```css
div.anrghg-thank-you > div.anrghg-inner-thank-you {
	color: $l_s_color;
	background-color: $l_s_background;
	font-size: $l_s_font_size;
	font-style: $l_s_font_style;
	font-weight: $l_s_font_weight;
	text-align: $l_s_text_align;
	max-width: $l_s_max_width;
	padding: $l_s_padding_top $l_s_padding_end $l_s_padding_bottom $l_s_padding_start;
	margin: $l_s_margin_top $l_s_margin_end $l_s_margin_bottom $l_s_margin_start;
	border: $l_s_border_width $l_s_border_style $l_s_border_color;
	border-radius: $l_s_radius_top $l_s_radius_right $l_s_radius_bottom $l_s_radius_left;
	box-shadow: $l_s_shadow_x_offset $l_s_shadow_y_offset $l_s_shadow_blur $l_s_shadow_spread $l_s_shadow_color;
}
```
The tooltips had many combinators like in this extract of affected CSS for anchor tooltips:
```css
.anrghg-tooltip-display-toggle:checked + .anrghg-complement-tooltip,
.anrghg-complement-referrer:hover > .anrghg-complement-tooltip,
.anrghg-complement-referrer:focus-within > .anrghg-complement-tooltip,
.anrghg-display-toggle:not(:checked) + .anrghg-complement-list .anrghg-complement-row:target .anrghg-complement-referrer:hover > .anrghg-complement-tooltip,
.anrghg-display-toggle:not(:checked) + .anrghg-complement-list .anrghg-complement-row:target .anrghg-complement-referrer:focus-within > .anrghg-complement-tooltip {
	visibility: visible;
	opacity: 1;
	transition: opacity $l_s_fade_in_duration $l_s_fade_in_function $l_s_fade_in_delay;
}
```
And also:
```css
@media screen and (max-width: $l_s_gen_breakpoint_width) {

	.anrghg-tooltip-display-toggle:checked + .anrghg-complement-tooltip,
	.anrghg-complement-referrer:hover > .anrghg-complement-tooltip,
	.anrghg-complement-referrer:focus-within > .anrghg-complement-tooltip {
		transition-delay: 0;
		transition-duration: 80ms;
	}

}
```
Then close to the same again for the separately configurable backlink tooltips.
