### ISSUE TITLE
The complex CSS is removed

### ISSUE THREAD

**Issue by rafaucau** [Automattic/amp-wp#7291]
### Bug Description

I have such CSS and it works fine on the standard version of the site:
```css 
:where(.container) {
   width: min(var(--container-max-width), 100% - calc(var(--container-padding) * 2));
   margin-inline: auto;
}
```

However, when I display the AMP version of the page, it is broken because there is only such CSS left in the `.container` class:
```css 
:where(.container) {
   margin-inline: auto;
}
```

I don't even see in the file preview that it was removed, so it's probably some kind of bug:
![image](https://user-images.githubusercontent.com/25438601/194908753-80c65382-045b-4d07-916e-eb6b6a258eed.png)
![image](https://user-images.githubusercontent.com/25438601/194908045-da94a8e2-ab0b-42bc-bf37-97375b4ea953.png)

### Expected Behaviour

It shouldn't be removed.

### PHP Version

8.1

### Plugin Version

2.3.0

### AMP plugin template mode

Transitional

### WordPress Version

6.0.2

### OS(s) Affected

All

### Browser(s) Affected

All

### Device(s) Affected

All

**Comment by thelovekesh** [comment]
I believe the problem arises from `100% - calc(var(—container-padding)* 2)` which the parser is unsure how to handle, but browsers are fairly intelligent and automatically display the desired results.

It should be possible for the parser to parse it as intended if you make it a little more precise.
```diff
:where(.container) {
-  width: min(var(--container-max-width), 100% - calc(var(--container-padding) * 2));
+  width: min(var(--container-max-width), calc(100% - calc(var(--container-padding) * 2)));
   margin-inline: auto;
}
```

**Comment by rafaucau** [comment]
Thanks, it helped! I'm using SCSS and had to additionally wrap it in `#{' '}` because the Sass compiler simplifies some things.
```scss
:where(.container) {
   width: #{'min(var(--container-max-width), calc(100% - calc(var(--container-padding) * 2)))'};
   margin-inline: auto;
}
```

I think this should be fixed in this plugin anyway, since the Sass compiler turns it into a shorter version by default and this is valid CSS.
