### ISSUE TITLE
Ensure block styles are applied properly in Legacy theme

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7497]
### Bug Description

With #7496 a fix was put in place for another fix in #7481. But both of these seem to be addressing a more fundamental problem in that block styles aren't yet applying properly to the Legacy theme template.

Namely, if those changes were removed, WordPress seems to be able to apply the proper styling if:

1. The max-width is removed from `.amp-wp-article`
2. The `is-layout-constrained` class is added to the `.amp-wp-article` element.
3. This style from TT3 is output:

```css
body .is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
    max-width: var(--wp--style--global--content-size);
    margin-left: auto !important;
    margin-right: auto !important;
}
```

This style appears to be generated from `theme.json`.

Applying these changes may allow us to remove additional patches from `style.php`. However, we'll need to make sure we don't break non-block styling (i.e. classic block).

### Expected Behaviour

Blocks should be styled correctly and consistently in Legacy theme without the need for one-off hacks.

### Plugin Version

2.4.1

### AMP plugin template mode

Reader
